# Backend port
server:
  port: ${BACKEND_PORT:6065}

spring:
  # Active profile
  profiles:
    active: ${PROFILE:dev}
  # Liquibase
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml
    enabled: true
    contexts: ${PROFILE:dev}
  # Multipart file upload
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 20MB
  # Database configuration
  datasource:
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  # Hibernate configuration
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

optifact:
  frontend:
    host: ${FRONTEND_HOST}
    port: ${FRONTEND_PORT}
  file:
    claim:
      rootDirectory: ${CLAIM_FILE_ROOT_DIR}
  jwt:
    issuer: ${JWT_ISSUER}
    secret: ${JWT_SECRET}
    access:
      expiration: ${JWT_EXPIRATION}
    refresh:
      expiration: ${JWT_REFRESH_EXPIRATION}

logging:
  level:
    org.springframework.security: DEBUG