BACKEND_PORT: ${BACKEND_PORT}
PROFILE: ${PROFILE}
DB_HOST: ${DB_HOST}
DB_PORT: ${DB_PORT}
DB_NAME: ${DB_NAME}
DB_USERNAME: ${DB_USERNAME}
DB_PASSWORD: ${DB_PASSWORD}
FRONTEND_HOST: ${FRONTEND_HOST}
FRONTEND_PORT: ${FRONTEND_PORT}
CLAIM_FILE_ROOT_DIR: ${user.home}/optifact/claimFiles
