export interface CountryItem { code: string; name: string; flag: string; dial: string; phoneFormat: string }

// Liste des pays du monde (ISO 3166-1 alpha-2) en français, avec indicatifs téléphoniques.
// phoneFormat: motif simple destiné à l'affichage/masque (pas une validation stricte).
// Par défaut: format E.164 générique "+###########" (jusqu'à ~15 chiffres) si inconnu.
// Liste de base non triée; l'ordre d'affichage est construit plus bas pour prioriser l'Afrique centrale.
const ALL_COUNTRIES: CountryItem[] = [
  // Afrique centrale (prioritaires)
  { code: 'CM', name: 'Cameroun', flag: '🇨🇲', dial: '+237', phoneFormat: '+237 ### ### ###' },
  { code: 'CF', name: 'République centrafricaine', flag: '🇨🇫', dial: '+236', phoneFormat: '+236 ## ## ## ##' },
  { code: 'TD', name: 'Tchad', flag: '🇹🇩', dial: '+235', phoneFormat: '+235 ## ## ## ##' },
  { code: 'CG', name: 'Congo', flag: '🇨🇬', dial: '+242', phoneFormat: '+242 ## ### ####' },
  { code: 'CD', name: 'Rép. dém. du Congo', flag: '🇨🇩', dial: '+243', phoneFormat: '+243 ### ### ###' },
  { code: 'GQ', name: 'Guinée équatoriale', flag: '🇬🇶', dial: '+240', phoneFormat: '+240 ### ####' },
  { code: 'GA', name: 'Gabon', flag: '🇬🇦', dial: '+241', phoneFormat: '+241 ## ## ## ##' },
  { code: 'ST', name: 'Sao Tomé-et-Principe', flag: '🇸🇹', dial: '+239', phoneFormat: '+239 ### ####' },
  // Europe
  { code: 'FR', name: 'France', flag: '🇫🇷', dial: '+33', phoneFormat: '+33 # ## ## ## ##' },
  { code: 'BE', name: 'Belgique', flag: '🇧🇪', dial: '+32', phoneFormat: '+32 ## ## ## ##' },
  { code: 'CH', name: 'Suisse', flag: '🇨🇭', dial: '+41', phoneFormat: '+41 ## ### ## ##' },
  { code: 'DE', name: 'Allemagne', flag: '🇩🇪', dial: '+49', phoneFormat: '+49 #### ########' },
  { code: 'ES', name: 'Espagne', flag: '🇪🇸', dial: '+34', phoneFormat: '+34 ### ## ## ##' },
  { code: 'IT', name: 'Italie', flag: '🇮🇹', dial: '+39', phoneFormat: '+39 ### #### ###' },
  { code: 'GB', name: 'Royaume-Uni', flag: '🇬🇧', dial: '+44', phoneFormat: '+44 #### ######' },
  { code: 'IE', name: 'Irlande', flag: '🇮🇪', dial: '+353', phoneFormat: '+353 ## ### ####' },
  { code: 'NL', name: 'Pays-Bas', flag: '🇳🇱', dial: '+31', phoneFormat: '+31 ## ### ####' },
  { code: 'LU', name: 'Luxembourg', flag: '🇱🇺', dial: '+352', phoneFormat: '+352 ### ### ###' },
  { code: 'PT', name: 'Portugal', flag: '🇵🇹', dial: '+351', phoneFormat: '+351 ### ### ###' },
  { code: 'AT', name: 'Autriche', flag: '🇦🇹', dial: '+43', phoneFormat: '+43 ### #### ####' },
  { code: 'SE', name: 'Suède', flag: '🇸🇪', dial: '+46', phoneFormat: '+46 ## ### ####' },
  { code: 'NO', name: 'Norvège', flag: '🇳🇴', dial: '+47', phoneFormat: '+47 ### ## ###' },
  { code: 'DK', name: 'Danemark', flag: '🇩🇰', dial: '+45', phoneFormat: '+45 ## ## ## ##' },
  { code: 'FI', name: 'Finlande', flag: '🇫🇮', dial: '+358', phoneFormat: '+358 ## ### ####' },
  { code: 'PL', name: 'Pologne', flag: '🇵🇱', dial: '+48', phoneFormat: '+48 ### ### ###' },
  { code: 'CZ', name: 'Tchéquie', flag: '🇨🇿', dial: '+420', phoneFormat: '+420 ### ### ###' },
  { code: 'SK', name: 'Slovaquie', flag: '🇸🇰', dial: '+421', phoneFormat: '+421 ### ### ###' },
  { code: 'HU', name: 'Hongrie', flag: '🇭🇺', dial: '+36', phoneFormat: '+36 ## ### ####' },
  { code: 'RO', name: 'Roumanie', flag: '🇷🇴', dial: '+40', phoneFormat: '+40 ### ### ###' },
  { code: 'BG', name: 'Bulgarie', flag: '🇧🇬', dial: '+359', phoneFormat: '+359 ### ### ###' },
  { code: 'GR', name: 'Grèce', flag: '🇬🇷', dial: '+30', phoneFormat: '+30 ### #### ###' },
  { code: 'HR', name: 'Croatie', flag: '🇭🇷', dial: '+385', phoneFormat: '+385 ## ### ####' },
  { code: 'SI', name: 'Slovénie', flag: '🇸🇮', dial: '+386', phoneFormat: '+386 ## ### ###' },
  { code: 'BA', name: 'Bosnie-Herzégovine', flag: '🇧🇦', dial: '+387', phoneFormat: '+387 ## ### ###' },
  { code: 'RS', name: 'Serbie', flag: '🇷🇸', dial: '+381', phoneFormat: '+381 ## ### ####' },
  { code: 'ME', name: 'Monténégro', flag: '🇲🇪', dial: '+382', phoneFormat: '+382 ## ### ###' },
  { code: 'MK', name: 'Macédoine du Nord', flag: '🇲🇰', dial: '+389', phoneFormat: '+389 ## ### ###' },
  { code: 'AL', name: 'Albanie', flag: '🇦🇱', dial: '+355', phoneFormat: '+355 ## ### ####' },
  { code: 'IS', name: 'Islande', flag: '🇮🇸', dial: '+354', phoneFormat: '+354 ### ####' },
  { code: 'EE', name: 'Estonie', flag: '🇪🇪', dial: '+372', phoneFormat: '+372 #### ####' },
  { code: 'LV', name: 'Lettonie', flag: '🇱🇻', dial: '+371', phoneFormat: '+371 ## ### ###' },
  { code: 'LT', name: 'Lituanie', flag: '🇱🇹', dial: '+370', phoneFormat: '+370 ### #####' },
  { code: 'UA', name: 'Ukraine', flag: '🇺🇦', dial: '+380', phoneFormat: '+380 ## ### ####' },
  { code: 'BY', name: 'Biélorussie', flag: '🇧🇾', dial: '+375', phoneFormat: '+375 ## ### ####' },
  { code: 'MD', name: 'Moldavie', flag: '🇲🇩', dial: '+373', phoneFormat: '+373 #### ####' },

  // Amériques
  { code: 'US', name: 'États-Unis', flag: '🇺🇸', dial: '+1', phoneFormat: '+1 (###) ###-####' },
  { code: 'CA', name: 'Canada', flag: '🇨🇦', dial: '+1', phoneFormat: '+1 (###) ###-####' },
  { code: 'MX', name: 'Mexique', flag: '🇲🇽', dial: '+52', phoneFormat: '+52 ## #### ####' },
  { code: 'BR', name: 'Brésil', flag: '🇧🇷', dial: '+55', phoneFormat: '+55 ## ##### ####' },
  { code: 'AR', name: 'Argentine', flag: '🇦🇷', dial: '+54', phoneFormat: '+54 ## #### ####' },
  { code: 'CL', name: 'Chili', flag: '🇨🇱', dial: '+56', phoneFormat: '+56 # #### ####' },
  { code: 'CO', name: 'Colombie', flag: '🇨🇴', dial: '+57', phoneFormat: '+57 ### ### ####' },
  { code: 'PE', name: 'Pérou', flag: '🇵🇪', dial: '+51', phoneFormat: '+51 ### ### ###' },
  { code: 'VE', name: 'Venezuela', flag: '🇻🇪', dial: '+58', phoneFormat: '+58 ### ### ####' },
  { code: 'UY', name: 'Uruguay', flag: '🇺🇾', dial: '+598', phoneFormat: '+598 # ### ####' },
  { code: 'PY', name: 'Paraguay', flag: '🇵🇾', dial: '+595', phoneFormat: '+595 ### ######' },
  { code: 'BO', name: 'Bolivie', flag: '🇧🇴', dial: '+591', phoneFormat: '+591 ### ######' },
  { code: 'EC', name: 'Équateur', flag: '🇪🇨', dial: '+593', phoneFormat: '+593 ## ### ####' },
  { code: 'GT', name: 'Guatemala', flag: '🇬🇹', dial: '+502', phoneFormat: '+502 #### ####' },
  { code: 'HN', name: 'Honduras', flag: '🇭🇳', dial: '+504', phoneFormat: '+504 #### ####' },
  { code: 'NI', name: 'Nicaragua', flag: '🇳🇮', dial: '+505', phoneFormat: '+505 #### ####' },
  { code: 'SV', name: 'Salvador', flag: '🇸🇻', dial: '+503', phoneFormat: '+503 #### ####' },
  { code: 'CR', name: 'Costa Rica', flag: '🇨🇷', dial: '+506', phoneFormat: '+506 #### ####' },
  { code: 'PA', name: 'Panama', flag: '🇵🇦', dial: '+507', phoneFormat: '+507 ### ####' },
  { code: 'CU', name: 'Cuba', flag: '🇨🇺', dial: '+53', phoneFormat: '+53 ### ######' },
  { code: 'DO', name: 'République dominicaine', flag: '🇩🇴', dial: '+1', phoneFormat: '+1 (###) ###-####' },
  { code: 'JM', name: 'Jamaïque', flag: '🇯🇲', dial: '+1', phoneFormat: '+1 (###) ###-####' },

  // Afrique
  { code: 'MA', name: 'Maroc', flag: '🇲🇦', dial: '+212', phoneFormat: '+212 ## #### ###' },
  { code: 'DZ', name: 'Algérie', flag: '🇩🇿', dial: '+213', phoneFormat: '+213 ## ### ####' },
  { code: 'TN', name: 'Tunisie', flag: '🇹🇳', dial: '+216', phoneFormat: '+216 ## ### ###' },
  { code: 'SN', name: 'Sénégal', flag: '🇸🇳', dial: '+221', phoneFormat: '+221 ## ### ####' },
  { code: 'CI', name: "Côte d'Ivoire", flag: '🇨🇮', dial: '+225', phoneFormat: '+225 ## ## ## ##' },
  { code: 'GN', name: 'Guinée', flag: '🇬🇳', dial: '+224', phoneFormat: '+224 ### ## ## ##' },
  { code: 'ML', name: 'Mali', flag: '🇲🇱', dial: '+223', phoneFormat: '+223 ## ## ####' },
  { code: 'NE', name: 'Niger', flag: '🇳🇪', dial: '+227', phoneFormat: '+227 ## ## ## ##' },
  { code: 'NG', name: 'Nigéria', flag: '🇳🇬', dial: '+234', phoneFormat: '+234 ### ### ####' },
  { code: 'GH', name: 'Ghana', flag: '🇬🇭', dial: '+233', phoneFormat: '+233 ## ### ####' },
  { code: 'KE', name: 'Kenya', flag: '🇰🇪', dial: '+254', phoneFormat: '+254 ### ######' },
  { code: 'ET', name: 'Éthiopie', flag: '🇪🇹', dial: '+251', phoneFormat: '+251 ## ### ####' },
  { code: 'UG', name: 'Ouganda', flag: '🇺🇬', dial: '+256', phoneFormat: '+256 ### ######' },
  { code: 'TZ', name: 'Tanzanie', flag: '🇹🇿', dial: '+255', phoneFormat: '+255 ## ### ####' },
  { code: 'ZA', name: 'Afrique du Sud', flag: '🇿🇦', dial: '+27', phoneFormat: '+27 ## ### ####' },
  { code: 'AO', name: 'Angola', flag: '🇦🇴', dial: '+244', phoneFormat: '+244 ### ### ###' },
  { code: 'BF', name: 'Burkina Faso', flag: '🇧🇫', dial: '+226', phoneFormat: '+226 ## ## ## ##' },
  { code: 'BJ', name: 'Bénin', flag: '🇧🇯', dial: '+229', phoneFormat: '+229 ## ## ## ##' },
  { code: 'TG', name: 'Togo', flag: '🇹🇬', dial: '+228', phoneFormat: '+228 ## ## ## ##' },
  { code: 'MW', name: 'Malawi', flag: '🇲🇼', dial: '+265', phoneFormat: '+265 # #### ####' },
  { code: 'ZM', name: 'Zambie', flag: '🇿🇲', dial: '+260', phoneFormat: '+260 ### ######' },
  { code: 'ZW', name: 'Zimbabwe', flag: '🇿🇼', dial: '+263', phoneFormat: '+263 ## ######' },
  { code: 'RW', name: 'Rwanda', flag: '🇷🇼', dial: '+250', phoneFormat: '+250 ### ### ###' },
  { code: 'MU', name: 'Maurice', flag: '🇲🇺', dial: '+230', phoneFormat: '+230 #### ####' },
  { code: 'SC', name: 'Seychelles', flag: '🇸🇨', dial: '+248', phoneFormat: '+248 # ### ###' },
  { code: 'MG', name: 'Madagascar', flag: '🇲🇬', dial: '+261', phoneFormat: '+261 ## ## ####' },
  { code: 'KM', name: 'Comores', flag: '🇰🇲', dial: '+269', phoneFormat: '+269 ## ## ##' },

  // Asie
  { code: 'CN', name: 'Chine', flag: '🇨🇳', dial: '+86', phoneFormat: '+86 ### #### ####' },
  { code: 'JP', name: 'Japon', flag: '🇯🇵', dial: '+81', phoneFormat: '+81 ## #### ####' },
  { code: 'KR', name: 'Corée du Sud', flag: '🇰🇷', dial: '+82', phoneFormat: '+82 ## #### ####' },
  { code: 'IN', name: 'Inde', flag: '🇮🇳', dial: '+91', phoneFormat: '+91 ##### #####' },
  { code: 'PK', name: 'Pakistan', flag: '🇵🇰', dial: '+92', phoneFormat: '+92 ### #### ###' },
  { code: 'BD', name: 'Bangladesh', flag: '🇧🇩', dial: '+880', phoneFormat: '+880 #### ######' },
  { code: 'LK', name: 'Sri Lanka', flag: '🇱🇰', dial: '+94', phoneFormat: '+94 ## ### ####' },
  { code: 'NP', name: 'Népal', flag: '🇳🇵', dial: '+977', phoneFormat: '+977 ## #######' },
  { code: 'BT', name: 'Bhoutan', flag: '🇧🇹', dial: '+975', phoneFormat: '+975 ## ### ###' },
  { code: 'MM', name: 'Birmanie', flag: '🇲🇲', dial: '+95', phoneFormat: '+95 ## ### ####' },
  { code: 'TH', name: 'Thaïlande', flag: '🇹🇭', dial: '+66', phoneFormat: '+66 ## ### ####' },
  { code: 'VN', name: 'Viêt Nam', flag: '🇻🇳', dial: '+84', phoneFormat: '+84 ## #### ###' },
  { code: 'PH', name: 'Philippines', flag: '🇵🇭', dial: '+63', phoneFormat: '+63 ### ### ####' },
  { code: 'MY', name: 'Malaisie', flag: '🇲🇾', dial: '+60', phoneFormat: '+60 ## ### ####' },
  { code: 'SG', name: 'Singapour', flag: '🇸🇬', dial: '+65', phoneFormat: '+65 #### ####' },
  { code: 'ID', name: 'Indonésie', flag: '🇮🇩', dial: '+62', phoneFormat: '+62 ## ### ####' },
  { code: 'KH', name: 'Cambodge', flag: '🇰🇭', dial: '+855', phoneFormat: '+855 ## ### ###' },
  { code: 'LA', name: 'Laos', flag: '🇱🇦', dial: '+856', phoneFormat: '+856 ## ### ###' },
  { code: 'TW', name: 'Taïwan', flag: '🇹🇼', dial: '+886', phoneFormat: '+886 #### ####' },
  { code: 'HK', name: 'Hong Kong', flag: '🇭🇰', dial: '+852', phoneFormat: '+852 #### ####' },
  { code: 'MO', name: 'Macao', flag: '🇲🇴', dial: '+853', phoneFormat: '+853 #### ####' },
  { code: 'AE', name: 'Émirats arabes unis', flag: '🇦🇪', dial: '+971', phoneFormat: '+971 ## ### ####' },
  { code: 'SA', name: 'Arabie saoudite', flag: '🇸🇦', dial: '+966', phoneFormat: '+966 ## ### ####' },
  { code: 'QA', name: 'Qatar', flag: '🇶🇦', dial: '+974', phoneFormat: '+974 #### ####' },
  { code: 'KW', name: 'Koweït', flag: '🇰🇼', dial: '+965', phoneFormat: '+965 #### ####' },
  { code: 'OM', name: 'Oman', flag: '🇴🇲', dial: '+968', phoneFormat: '+968 #### ####' },
  { code: 'BH', name: 'Bahreïn', flag: '🇧🇭', dial: '+973', phoneFormat: '+973 #### ####' },
  { code: 'JO', name: 'Jordanie', flag: '🇯🇴', dial: '+962', phoneFormat: '+962 # #### ####' },
  { code: 'LB', name: 'Liban', flag: '🇱🇧', dial: '+961', phoneFormat: '+961 ## ### ###' },
  { code: 'IR', name: 'Iran', flag: '🇮🇷', dial: '+98', phoneFormat: '+98 ## ### ####' },
  { code: 'IQ', name: 'Irak', flag: '🇮🇶', dial: '+964', phoneFormat: '+964 ### ### ####' },
  { code: 'IL', name: 'Israël', flag: '🇮🇱', dial: '+972', phoneFormat: '+972 ## ### ####' },
  { code: 'TR', name: 'Turquie', flag: '🇹🇷', dial: '+90', phoneFormat: '+90 ### ### ####' },
  { code: 'KZ', name: 'Kazakhstan', flag: '🇰🇿', dial: '+7', phoneFormat: '+7 ### ### ## ##' },
  { code: 'KG', name: 'Kirghizistan', flag: '🇰🇬', dial: '+996', phoneFormat: '+996 ### ### ###' },
  { code: 'UZ', name: 'Ouzbékistan', flag: '🇺🇿', dial: '+998', phoneFormat: '+998 ## ### ####' },
  { code: 'TM', name: 'Turkménistan', flag: '🇹🇲', dial: '+993', phoneFormat: '+993 ## ### ###' },
  { code: 'TJ', name: 'Tadjikistan', flag: '🇹🇯', dial: '+992', phoneFormat: '+992 ## ### ####' },
  { code: 'AF', name: 'Afghanistan', flag: '🇦🇫', dial: '+93', phoneFormat: '+93 ## ### ####' },

  // Océanie
  { code: 'AU', name: 'Australie', flag: '🇦🇺', dial: '+61', phoneFormat: '+61 # #### ####' },
  { code: 'NZ', name: 'Nouvelle-Zélande', flag: '🇳🇿', dial: '+64', phoneFormat: '+64 ## ### ####' },
  { code: 'PG', name: 'Papouasie-Nouvelle-Guinée', flag: '🇵🇬', dial: '+675', phoneFormat: '+675 ### ####' },
  { code: 'FJ', name: 'Fidji', flag: '🇫🇯', dial: '+679', phoneFormat: '+679 #### ####' },
  { code: 'WS', name: 'Samoa', flag: '🇼🇸', dial: '+685', phoneFormat: '+685 ## ####' },
  { code: 'TO', name: 'Tonga', flag: '🇹🇴', dial: '+676', phoneFormat: '+676 #####' },
  { code: 'SB', name: 'Salomon', flag: '🇸🇧', dial: '+677', phoneFormat: '+677 #####' },
  { code: 'VU', name: 'Vanuatu', flag: '🇻🇺', dial: '+678', phoneFormat: '+678 #####' },

  // Moyen-Orient & autres territoires
  { code: 'EG', name: 'Égypte', flag: '🇪🇬', dial: '+20', phoneFormat: '+20 ## #### ###' },
  { code: 'SD', name: 'Soudan', flag: '🇸🇩', dial: '+249', phoneFormat: '+249 ## ### ####' },
  { code: 'SS', name: 'Soudan du Sud', flag: '🇸🇸', dial: '+211', phoneFormat: '+211 ## ### ####' },
  { code: 'YE', name: 'Yémen', flag: '🇾🇪', dial: '+967', phoneFormat: '+967 ### ### ###' },
  { code: 'SY', name: 'Syrie', flag: '🇸🇾', dial: '+963', phoneFormat: '+963 ## #### ###' },
  { code: 'PS', name: 'Palestine', flag: '🇵🇸', dial: '+970', phoneFormat: '+970 ## ### ####' },

  // Par défaut pour les pays non listés explicitement (placeholder générique)
  // Note: Pour couvrir « tous les pays », ajoutez ici d'autres entrées si nécessaire.
];

// Codes ISO des pays de l'Afrique centrale à prioriser
const CENTRAL_AFRICA_CODES = ['CM','CF','TD','CG','CD','GQ','GA','ST'] as const;

// Export trié: d'abord Afrique centrale (ordre alphabétique par nom), puis le reste (ordre alphabétique par nom)
export const COUNTRIES: CountryItem[] = [
  ...ALL_COUNTRIES
    .filter(c => CENTRAL_AFRICA_CODES.includes(c.code as any))
    .sort((a, b) => a.name.localeCompare(b.name, 'fr')),
  ...ALL_COUNTRIES
    .filter(c => !CENTRAL_AFRICA_CODES.includes(c.code as any))
    .sort((a, b) => a.name.localeCompare(b.name, 'fr')),
];
